# TODO: add papers by configuration file
base_url: "https://arxiv.paperswithcode.com/api/v0/papers/"
user_name: "XikunHuang"
repo_name: "daily_paper"
show_authors: True
show_links: True
show_badge: False
max_results: 10

publish_readme: True
publish_gitpage: True
publish_wechat: False

# file paths
json_readme_path: './docs/daily-paper.json'
json_gitpage_path: './docs/daily-paper-web.json'
json_wechat_path: './docs/daily-paper-wechat.json'

md_readme_path: 'README.md'
md_gitpage_path: './docs/index.md'
md_wechat_path: './docs/wechat.md'

# keywords to search
keywords:
    "Diffusion":
        filters: ["diffusion", "flow"]
    "Graph":
        filters: ["graph generation", "graph neural network"]
